// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApLdIepqIjkLFBWbCLokndcd0jikrKyiI',
    appId: '1:1012480201797:web:3eece4a56d3f46cc85bf2c',
    messagingSenderId: '1012480201797',
    projectId: 'fashion-store-a4362',
    authDomain: 'fashion-store-a4362.firebaseapp.com',
    storageBucket: 'fashion-store-a4362.firebasestorage.app',
    measurementId: 'G-C0NGM9CRRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-xYug_RGruqH4xS41A6-yON0HlEnTfRU',
    appId: '1:1012480201797:android:0fc4358b81584fe985bf2c',
    messagingSenderId: '1012480201797',
    projectId: 'fashion-store-a4362',
    storageBucket: 'fashion-store-a4362.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGG2Ym8tzS9WdD98IWngOfZ6wOsq2rD5E',
    appId: '1:1012480201797:ios:24b5716fdaa3fff385bf2c',
    messagingSenderId: '1012480201797',
    projectId: 'fashion-store-a4362',
    storageBucket: 'fashion-store-a4362.firebasestorage.app',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGG2Ym8tzS9WdD98IWngOfZ6wOsq2rD5E',
    appId: '1:1012480201797:ios:24b5716fdaa3fff385bf2c',
    messagingSenderId: '1012480201797',
    projectId: 'fashion-store-a4362',
    storageBucket: 'fashion-store-a4362.firebasestorage.app',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApLdIepqIjkLFBWbCLokndcd0jikrKyiI',
    appId: '1:1012480201797:web:80495b53e51c801585bf2c',
    messagingSenderId: '1012480201797',
    projectId: 'fashion-store-a4362',
    authDomain: 'fashion-store-a4362.firebaseapp.com',
    storageBucket: 'fashion-store-a4362.firebasestorage.app',
    measurementId: 'G-4331P8G8R8',
  );
}
